version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/AliyunContainerService/open-service-broker-alibabacloud
    steps:
    - checkout
    - run: go vet ./...
    - run: go build
    - run: go test ./...

