# Default values for alibabacloud-servicebroker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  # repository: registry.cn-hangzhou.aliyuncs.com/service-catalog/alibabacloud-servicebroker
  repository: registry.cn-hangzhou.aliyuncs.com/testfengyu/testfengyu
  tag: 0.1
  pullPolicy: Always
service:
  name: alibabacloud-servicebroker
  type: ClusterIP
  externalPort: 80
  internalPort: 8005
  runBrokers: polardb-broker
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
etcdImage: registry.cn-hangzhou.aliyuncs.com/service-catalog/etcd:v3.3.2
etcd:
  # Whether to embed an etcd container in the apiserver pod
  # THIS IS INADEQUATE FOR PRODUCTION USE!
  useEmbedded: true
  # etcd URL(s); override this if NOT using embedded etcd
  servers: http://localhost:2379
  # etcd persistence options IF using embedded etcd
  persistence:
    enabled: false
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 4Gi
## Whether to automatically register this broker with the Kubernetes Service Catalog. If true,
## the Kubernetes Service Catalog must already be installed on the cluster.
## Marking this option false is useful for scenarios wherein one wishes to host
## the broker in a separate cluster than the Service Catalog (or other client)
## that will access it.
registerBroker: true
