apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: rds-binding
  namespace: default
spec:
  instanceRef:
    name: rds-mysql-1
  secretName: rds-instance-credentials
  parameters:
    Username:
    Password:
