{{- if .Values.registerBroker }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: alibabacloud-servicebroker
spec:
  url: http://{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
